feat: web sockets endpoints for live analytics
Software-Engineering-Jagiellonian/django-celery-frege-poc pull request #26
Opened 2022-05-15 15:44 UTC by apardyl

Depends on #13 and #25 and should be merged after them.

rel: https://jira.frege.ii.uj.edu.pl/browse/FREGE-143

2022-05-17 23:04 UTC, ConsoleRunner requested changes
Tests are not passing (we should probably set up CI), next time please mark your PR as draft if you didn't finish working on it.

2022-05-18 08:03 UTC, apardyl commented on backend/fregepoc/asgi.py
> +    "websocket": AuthMiddlewareStack(
CSRF not CORS, but good point. Added.

2022-05-18 08:12 UTC, apardyl commented
> Tests are not passing (we should probably set up CI), next time please mark your PR as draft if you didn't finish working on it.

It seems there is a bug in either pytest or django, that causes database_sync_to_async operations to break test isolation in some cases and leave artefacts in database after the test, see https://github.com/pytest-dev/pytest-django/issues/580
I've switched all asyncio tests to use real database transactions instead of `django.test.TestCase`-like noops, it should work every time now.

Also this PR was review ready the time it was submitted, this pytest/django bug did not manifest first time when I run pytest.

2022-05-18 18:21 UTC, ConsoleRunner approved these changes

2022-05-18 18:26 UTC, merged